/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Sistema.Funcionario;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbnNomeFuncionario = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        lbnEndFuncionario = new javax.swing.JLabel();
        txtEndFuncionario = new javax.swing.JTextField();
        lbnCpfFuncionario = new javax.swing.JLabel();
        txtCpfFuncionario = new javax.swing.JTextField();
        lbnTelFuncionario = new javax.swing.JLabel();
        txtTelFuncionario = new javax.swing.JTextField();
        lbnIdUsuarioFuncionario = new javax.swing.JLabel();
        txtIdUsuarioFunciorario = new javax.swing.JTextField();
        lbnIdCargoFuncionario = new javax.swing.JLabel();
        txtIdCargoFuncionario = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Funcionário");

        lbnNomeFuncionario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbnNomeFuncionario.setText("Nome:");

        lbnEndFuncionario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbnEndFuncionario.setText("Endereco:");

        lbnCpfFuncionario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbnCpfFuncionario.setText("CPF:");

        lbnTelFuncionario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbnTelFuncionario.setText("Telefone:");

        lbnIdUsuarioFuncionario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbnIdUsuarioFuncionario.setText("Id de Usuario:");

        lbnIdCargoFuncionario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbnIdCargoFuncionario.setText("Id de Cargo:");

        btnLimpar.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbnNomeFuncionario)
                            .addComponent(lbnEndFuncionario)
                            .addComponent(lbnCpfFuncionario)
                            .addComponent(lbnIdUsuarioFuncionario))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeFuncionario)
                            .addComponent(txtEndFuncionario)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdUsuarioFunciorario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbnTelFuncionario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbnIdCargoFuncionario)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtIdCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(193, 193, 193))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnNomeFuncionario)
                    .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnEndFuncionario)
                    .addComponent(txtEndFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnTelFuncionario)
                    .addComponent(txtTelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnCpfFuncionario))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnIdUsuarioFuncionario)
                    .addComponent(txtIdUsuarioFunciorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnIdCargoFuncionario)
                    .addComponent(txtIdCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair)
                    .addComponent(btnCadastrar)
                    .addComponent(btnConsultar))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            // Solicita o idFuncionario ao usuário
            String idFuncionarioStr = JOptionPane.showInputDialog(null, "Digite o ID do funcionário a ser excluído:");

            // Verifica se o usuário cancelou a operação
            if (idFuncionarioStr == null) {
                return;
            }

            // Valida se o idFuncionario é um número válido
            if (!idFuncionarioStr.matches("\\d+")) {
                JOptionPane.showMessageDialog(null, "Por favor, insira um número válido para o ID do funcionário.");
                return;
            }

            int idFuncionario = Integer.parseInt(idFuncionarioStr);

            // Chama o método para excluir o funcionário
            Funcionario funcionario = new Funcionario();
            boolean excluido = funcionario.excluirFuncionario(idFuncionario);
            if (excluido) {
                // Limpa os campos após a exclusão
                limparCampos();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao converter o ID do funcionário para número: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        // Verificar se todos os campos estão preenchidos
        if (txtNomeFuncionario.getText().isEmpty()
                || txtEndFuncionario.getText().isEmpty()
                || txtCpfFuncionario.getText().isEmpty()
                || txtTelFuncionario.getText().isEmpty()
                || txtIdUsuarioFunciorario.getText().isEmpty()
                || txtIdCargoFuncionario.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos antes de cadastrar o funcionário.");
            return; // Encerra o método se algum campo estiver vazio
        }

        // Caso todos os campos estejam preenchidos, prossegue com o cadastro
        Funcionario funcionario = new Funcionario();
        funcionario.setNomeFuncionario(txtNomeFuncionario.getText());
        funcionario.setEndereco(txtEndFuncionario.getText());
        funcionario.setCpf(txtCpfFuncionario.getText());
        funcionario.setTelefone(txtTelFuncionario.getText());
        funcionario.setUsuarioIdUsuario(Integer.parseInt(txtIdUsuarioFunciorario.getText()));
        funcionario.setCargoIdCargo(Integer.parseInt(txtIdCargoFuncionario.getText()));

        boolean cadastrado = funcionario.cadastrarFuncionario();
        if (cadastrado) {
            JOptionPane.showMessageDialog(null, "Funcionário cadastrado com sucesso.");
            // Limpar campos
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar funcionário.");
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        try {
            // Solicita o idFuncionario ao usuário
            String idFuncionarioStr = JOptionPane.showInputDialog(null, "Digite o ID do funcionário:");

            // Verifica se o usuário cancelou a operação
            if (idFuncionarioStr == null) {
                return;
            }

            // Valida se o idFuncionario é um número válido
            if (!idFuncionarioStr.matches("\\d+")) {
                JOptionPane.showMessageDialog(null, "Por favor, insira um número válido para o ID do funcionário.");
                return;
            }

            int idFuncionario = Integer.parseInt(idFuncionarioStr);

            // Chama o método para consultar o funcionário
            Funcionario funcionario = new Funcionario();
            Funcionario funcionarioConsultado = funcionario.consultarFuncionario(idFuncionario);
            if (funcionarioConsultado != null) {
                // Exibe as informações na tela
                txtNomeFuncionario.setText(funcionarioConsultado.getNomeFuncionario());
                txtEndFuncionario.setText(funcionarioConsultado.getEndereco());
                txtCpfFuncionario.setText(funcionarioConsultado.getCpf());
                txtTelFuncionario.setText(funcionarioConsultado.getTelefone());
                txtIdUsuarioFunciorario.setText(String.valueOf(funcionarioConsultado.getUsuarioIdUsuario()));
                txtIdCargoFuncionario.setText(String.valueOf(funcionarioConsultado.getCargoIdCargo()));
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao converter o ID do funcionário para número: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void limparCampos() {
        txtNomeFuncionario.setText("");
        txtEndFuncionario.setText("");
        txtCpfFuncionario.setText("");
        txtTelFuncionario.setText("");
        txtIdUsuarioFunciorario.setText("");
        txtIdCargoFuncionario.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbnCpfFuncionario;
    private javax.swing.JLabel lbnEndFuncionario;
    private javax.swing.JLabel lbnIdCargoFuncionario;
    private javax.swing.JLabel lbnIdUsuarioFuncionario;
    private javax.swing.JLabel lbnNomeFuncionario;
    private javax.swing.JLabel lbnTelFuncionario;
    private javax.swing.JTextField txtCpfFuncionario;
    private javax.swing.JTextField txtEndFuncionario;
    private javax.swing.JTextField txtIdCargoFuncionario;
    private javax.swing.JTextField txtIdUsuarioFunciorario;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtTelFuncionario;
    // End of variables declaration//GEN-END:variables
}
